- name: Ensure shared directories exist
  file:
    state: directory
    path: "{{ deploy_shared_dir }}/{{ item }}"
  with_items: "{{ deploy_shared_dirs }}"

- name: Link shared directories to next release
  file:
    state: link
    path: "{{ deploy_next_release_path }}/{{ item }}"
    src: "{{ deploy_shared_dir }}/{{ item }}"
    force: yes
  with_items: "{{ deploy_shared_dirs }}"

