---
- name: Pull sources from the repository.
  git:
    repo={{deploy.project.repo}}
    dest={{deploy.project.root}}/shared/cached-copy
    version={{deploy.project.branch}}
    accept_hostkey=yes
  when: deploy.project.scm == "git"

- name: Copying from local source
  synchronize: src={{deploy.project.source}} dest={{deploy.project.root}}/shared/cached-copy
  when: deploy.project.scm == "rsync"

- name: Create release directory
  command: mv {{deploy.project.root}}/shared/cached-copy {{deploy.project.root}}/releases/{{next_release}}
  args:
    chdir: "{{deploy.project.root}}/shared"

